export const DEVICE_CONFIG = {
  REPORT_INTERVAL_EMERGENCY_SEC: 10,
  REPORT_INTERVAL_MOVING_SEC: 120,
  REPORT_INTERVAL_STOPPED_SEC: 1800,
  CONFIG_POLL_INTERVAL_SEC: 30,
  STOP_DISTANCE_M: 40,
  STOP_SAMPLES_REQUIRED: 3,
  EMERGENCY_DURATION_MS: 30 * 60 * 1000,
} as const;
